# Generated by Django 5.2.4 on 2025-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loan_status',
            field=models.CharField(choices=[('NONE', 'No Loan'), ('ACTIVE', 'Active Loan'), ('COMPLETED', 'Completed Loan'), ('DEFAULTED', 'Defaulted Loan')], default='NONE', max_length=20),
        ),
    ]
