# Generated by Django 5.2.4 on 2025-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_income_customuser_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='loan_status',
            field=models.CharField(choices=[('NONE', 'No Loan'), ('ACTIVE', 'Active Loan'), ('COMPLETED', 'Completed Loan'), ('PENDING', 'Pending Loan'), ('DEFAULTED', 'Defaulted Loan')], default='NONE', max_length=20),
        ),
    ]
