# Generated by Django 5.2.4 on 2025-08-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_loan_status'),
        ('users', '0004_auto_20250822_2114'),
    ]

    operations = [
    ]
