# Generated by Django 5.2.4 on 2025-08-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_username_customuser_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='civil_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
