# Generated by Django 5.2.4 on 2025-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_civil_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
