# Generated by Django 5.2.4 on 2025-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_incomerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalytics',
            name='average_monthly_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated average monthly income based on user records.', max_digits=12),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='business_consistency_score',
            field=models.FloatField(default=0.0, help_text='A score from 0.0 to 1.0 indicating business activity consistency.'),
        ),
    ]
