# Generated by Django 5.2.4 on 2025-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending Analysis'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('UNREADABLE', 'Unreadable')], default='PENDING', max_length=20),
        ),
    ]
