# Generated by Django 5.2.4 on 2025-08-22 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('loaned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months_left', models.PositiveIntegerField()),
                ('next_repayment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
