# Generated by Django 5.2.4 on 2025-08-23 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('loaned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('months_left', models.IntegerField(default=12)),
                ('loan_term', models.IntegerField(default=12)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('next_repayment_due_date', models.DateField(blank=True, null=True)),
                ('repayment_status', models.CharField(choices=[('ON_TIME', 'On Time'), ('OVERDUE', 'Overdue')], default='ON_TIME', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
        ),
    ]
