# Generated by Django 5.2.4 on 2025-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='is_verified',
            new_name='is_verified_by_bank',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='next_repayment_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaned_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_repayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='months_left',
            field=models.IntegerField(default=0),
        ),
    ]
