# Generated by Django 5.2.4 on 2025-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_is_verified_loan_is_verified_by_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_term',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='months_left',
            field=models.IntegerField(default=12),
        ),
    ]
