# Generated by Django 5.2.4 on 2025-08-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_is_verified_by_bank_loan_status'),
        ('loans', '0003_loan_loan_term_loan_monthly_income_and_more'),
    ]

    operations = [
    ]
